'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    const generatedReacords = await queryInterface.bulkInsert('tasks', [
      {
        id: 1,
        topic: 'Изучение принципов ООП',
        description: 'Изучить принципы инкапсуляции, наследования, полиморфизма, абстракции и композиции. Подготовить отчет по каждому из принципов.',
        is_obligatory: true,
        lectures_number: 8,
        practical_number: 8,
        laboratory_number: 8,
        academic_module_id: 1,
      },
      {
        id: 2,
        topic: 'Применение ООП на практике',
        description: 'Реализовать программу, демонстрирующую работу принципов ООП',
        is_obligatory: true,
        lectures_number: 8,
        practical_number: 8,
        laboratory_number: 8,
        academic_module_id: 1,
      },
      {
        id: 3,
        topic: 'Принципы SOLID, изучение основ проектирования',
        description: 'Изучить принципы SOLID и подготовить отчет.',
        is_obligatory: true,
        lectures_number: 4,
        practical_number: 4,
        laboratory_number: 4,
        academic_module_id: 1,
      },
      {
        id: 4,
        topic: 'Проектирование баз данных',
        description: 'Построить инфологическую модель базы данных по вариантам.',
        is_obligatory: true,
        lectures_number: 2,
        practical_number: 2,
        laboratory_number: 2,
        academic_module_id: 2,
      },
      {
        id: 5,
        topic: 'Проектирование баз данных',
        description: 'Построить даталогическую модель базы данных по вариантам.',
        is_obligatory: true,
        lectures_number: 2,
        practical_number: 2,
        laboratory_number: 2,
        academic_module_id: 2,
      },
      {
        id: 6,
        topic: 'Язык SQL. DDL (Data Definition Language)',
        description: 'Описать таблицы на языке SQL (DDL) для спроетированной схемы базы данных.',
        is_obligatory: true,
        lectures_number: 8,
        practical_number: 8,
        laboratory_number: 8,
        academic_module_id: 2,
      },
      {
        id: 7,
        topic: 'DML (Data Manipulation Language)',
        description: 'Заполнить созданные таблицы тестовыми данными.',
        is_obligatory: true,
        lectures_number: 4,
        practical_number: 4,
        laboratory_number: 4,
        academic_module_id: 2,
      },
      {
        id: 8,
        topic: 'DML (Data Manipulation Language)',
        description: 'Выполнить выборку из базы данных для своего варианта.',
        is_obligatory: true,
        lectures_number: 4,
        practical_number: 4,
        laboratory_number: 4,
        academic_module_id: 2,
      },
      {
        id: 9,
        topic: 'Проектирование схемы базы даннах для информационной системы',
        description: 'Построить инфологическую и даталогическую модель базы данных для информационной системы.',
        is_obligatory: true,
        lectures_number: 4,
        practical_number: 4,
        laboratory_number: 4,
        academic_module_id: 3,
      },
      {
        id: 10,
        topic: 'Подключение к базе данных',
        description: 'Создать базу данных. Подключить проект к созданной базе данных.',
        is_obligatory: true,
        lectures_number: 4,
        practical_number: 4,
        laboratory_number: 4,
        academic_module_id: 3,
      },
      {
        id: 11,
        topic: 'Разработка составляющих информационной системы',
        description: 'Разработать модели, репозитории, сервисы и контроллеры для информационной системы.',
        is_obligatory: true,
        lectures_number: 12,
        practical_number: 12,
        laboratory_number: 12,
        academic_module_id: 3,
      },
      {
        id: 12,
        topic: 'Протокол TCP (Transmission Control Protocol)',
        description: 'Изучить протокол TCP (Transmission Control Protocol) и подготовить отчет по изученному материалу.',
        is_obligatory: true,
        lectures_number: 4,
        practical_number: 4,
        laboratory_number: 4,
        academic_module_id: 4,
      },
      {
        id: 13,
        topic: 'UDP (User Datagram Protocol)',
        description: 'Изучить протокол UDP (User Datagram Protocol) и подготовить отчет по изученному материалу.',
        is_obligatory: true,
        lectures_number: 4,
        practical_number: 4,
        laboratory_number: 4,
        academic_module_id: 4,
      },
      {
        id: 14,
        topic: 'HTTP (Hypertext Transfer Protocol)',
        description: 'Изучить протокол HTTP (Hypertext Transfer Protocol) и подготовить отчет по изученному материалу.',
        is_obligatory: true,
        lectures_number: 4,
        practical_number: 4,
        laboratory_number: 4,
        academic_module_id: 4,
      },
      {
        id: 15,
        topic: 'FTP (File Transfer Protocol)',
        description: 'Изучить протокол FTP (File Transfer Protocol) и подготовить отчет по изученному материалу.',
        is_obligatory: true,
        lectures_number: 4,
        practical_number: 4,
        laboratory_number: 4,
        academic_module_id: 4,
      },
      {
        id: 16,
        topic: 'SMTP (Simple Mail Transfer Protocol)',
        description: 'Изучить протокол SMTP (Simple Mail Transfer Protocol) и подготовить отчет по изученному материалу.',
        is_obligatory: true,
        lectures_number: 4,
        practical_number: 4,
        laboratory_number: 4,
        academic_module_id: 4,
      },
      {
        id: 17,
        topic: 'Утилита ls',
        description: 'Разработать программу на языке программирования C/C++ которая работает так же, как и стандартная утилита ls.',
        is_obligatory: true,
        lectures_number: 4,
        practical_number: 4,
        laboratory_number: 4,
        academic_module_id: 5,
      },
      {
        id: 18,
        topic: 'Утилита cd',
        description: 'Разработать программу на языке программирования C/C++ которая работает так же, как и стандартная утилита cd.',
        is_obligatory: true,
        lectures_number: 4,
        practical_number: 4,
        laboratory_number: 4,
        academic_module_id: 5,
      },
      {
        id: 19,
        topic: 'Утилита mkdir',
        description: 'Разработать программу на языке программирования C/C++ которая работает так же, как и стандартная утилита mkdir.',
        is_obligatory: true,
        lectures_number: 4,
        practical_number: 4,
        laboratory_number: 4,
        academic_module_id: 5,
      },
      {
        id: 20,
        topic: 'Утилита cp',
        description: 'Разработать программу на языке программирования C/C++ которая работает так же, как и стандартная утилита cp.',
        is_obligatory: true,
        lectures_number: 4,
        practical_number: 4,
        laboratory_number: 4,
        academic_module_id: 5,
      },
      {
        id: 21,
        topic: 'Утилита mv',
        description: 'Разработать программу на языке программирования C/C++ которая работает так же, как и стандартная утилита mv.',
        is_obligatory: true,
        lectures_number: 4,
        practical_number: 4,
        laboratory_number: 4,
        academic_module_id: 5,
      },
      {
        id: 22,
        topic: 'Соритовка слиянием',
        description: 'Разработать программу реализующую алгоритм сортировки слиянием.',
        is_obligatory: true,
        lectures_number: 4,
        practical_number: 4,
        laboratory_number: 4,
        academic_module_id: 6,
      },
      {
        id: 23,
        topic: 'Быстрая сортировка',
        description: 'Разработать программу реализующую алгоритм быстрой сортировки.',
        is_obligatory: true,
        lectures_number: 4,
        practical_number: 4,
        laboratory_number: 4,
        academic_module_id: 6,
      },
      {
        id: 24,
        topic: 'Бинарные деревья',
        description: 'Разработать структуру данных бинарное дерево.',
        is_obligatory: true,
        lectures_number: 4,
        practical_number: 4,
        laboratory_number: 4,
        academic_module_id: 6,
      },
      {
        id: 25,
        topic: 'Стек',
        description: 'Разработать структуру данных стек.',
        is_obligatory: true,
        lectures_number: 4,
        practical_number: 4,
        laboratory_number: 4,
        academic_module_id: 6,
      },
    ]);

    await queryInterface.sequelize.query(`SELECT setval('tasks_id_seq', 25)`);

    return generatedReacords;
  },

  async down(queryInterface, Sequelize) {
    return await queryInterface.bulkDelete('tasks', null, {});
  },
};
