'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    const generatedReacords = await queryInterface.bulkInsert('grades', [
      //Миша
      {
        id: 1,
        value: 10,
        student_id: 1,
        task_id: 1,
      },
      {
        id: 2,
        value: 9,
        student_id: 1,
        task_id: 2,
      },
      {
        id: 3,
        value: 8,
        student_id: 1,
        task_id: 3,
      },
      {
        id: 4,
        value: 9,
        student_id: 1,
        task_id: 4,
      },
      {
        id: 5,
        value: 10,
        student_id: 1,
        task_id: 5,
      },
      {
        id: 6,
        value: 9,
        student_id: 1,
        task_id: 6,
      },
      {
        id: 7,
        value: 8,
        student_id: 1,
        task_id: 7,
      },
      {
        id: 8,
        value: 9,
        student_id: 1,
        task_id: 8,
      },
      {
        id: 9,
        value: 8,
        student_id: 1,
        task_id: 9,
      },
      {
        id: 10,
        value: 10,
        student_id: 1,
        task_id: 10,
      },
      {
        id: 11,
        value: 9,
        student_id: 1,
        task_id: 11,
      },
      {
        id: 12,
        value: 10,
        student_id: 1,
        task_id: 12,
      },
      {
        id: 13,
        value: 9,
        student_id: 1,
        task_id: 13,
      },
      {
        id: 14,
        value: 10,
        student_id: 1,
        task_id: 14,
      },
      {
        id: 15,
        value: 9,
        student_id: 1,
        task_id: 15,
      },
      {
        id: 16,
        value: 9,
        student_id: 1,
        task_id: 16,
      },
      {
        id: 17,
        value: 8,
        student_id: 1,
        task_id: 17,
      },
      {
        id: 18,
        value: 8,
        student_id: 1,
        task_id: 18,
      },
      {
        id: 19,
        value: 10,
        student_id: 1,
        task_id: 19,
      },
      {
        id: 20,
        value: 10,
        student_id: 1,
        task_id: 20,
      },
      {
        id: 21,
        value: 9,
        student_id: 1,
        task_id: 21,
      },
      {
        id: 22,
        value: 9,
        student_id: 1,
        task_id: 22,
      },
      {
        id: 23,
        value: 10,
        student_id: 1,
        task_id: 23,
      },
      {
        id: 24,
        value: 9,
        student_id: 1,
        task_id: 24,
      },
      {
        id: 25,
        value: 10,
        student_id: 1,
        task_id: 25,
      },
      //Аня
      {
        id: 26,
        value: 10,
        student_id: 2,
        task_id: 1,
      },
      {
        id: 27,
        value: 9,
        student_id: 2,
        task_id: 2,
      },
      {
        id: 28,
        value: 8,
        student_id: 2,
        task_id: 3,
      },
      {
        id: 29,
        value: 9,
        student_id: 2,
        task_id: 4,
      },
      {
        id: 30,
        value: 10,
        student_id: 2,
        task_id: 5,
      },
      {
        id: 31,
        value: 10,
        student_id: 2,
        task_id: 6,
      },
      {
        id: 32,
        value: 9,
        student_id: 2,
        task_id: 7,
      },
      {
        id: 33,
        value: 10,
        student_id: 2,
        task_id: 8,
      },
      {
        id: 34,
        value: 9,
        student_id: 2,
        task_id: 9,
      },
      {
        id: 35,
        value: 10,
        student_id: 2,
        task_id: 10,
      },
      {
        id: 36,
        value: 8,
        student_id: 2,
        task_id: 11,
      },
      {
        id: 37,
        value: 9,
        student_id: 2,
        task_id: 12,
      },
      {
        id: 38,
        value: 10,
        student_id: 2,
        task_id: 13,
      },
      {
        id: 39,
        value: 10,
        student_id: 2,
        task_id: 14,
      },
      {
        id: 40,
        value: 10,
        student_id: 2,
        task_id: 15,
      },
      {
        id: 41,
        value: 9,
        student_id: 2,
        task_id: 16,
      },
      {
        id: 42,
        value: 10,
        student_id: 2,
        task_id: 17,
      },
      {
        id: 43,
        value: 9,
        student_id: 2,
        task_id: 18,
      },
      {
        id: 44,
        value: 10,
        student_id: 2,
        task_id: 19,
      },
      {
        id: 45,
        value: 10,
        student_id: 2,
        task_id: 20,
      },
      {
        id: 46,
        value: 8,
        student_id: 2,
        task_id: 21,
      },
      {
        id: 47,
        value: 10,
        student_id: 2,
        task_id: 22,
      },
      {
        id: 48,
        value: 9,
        student_id: 2,
        task_id: 23,
      },
      {
        id: 49,
        value: 10,
        student_id: 2,
        task_id: 24,
      },
      {
        id: 50,
        value: 9,
        student_id: 2,
        task_id: 25,
      },
      //Лабузов Никита
      {
        id: 51,
        value: 8,
        student_id: 3,
        task_id: 1,
      },
      {
        id: 52,
        value: 10,
        student_id: 3,
        task_id: 2,
      },
      {
        id: 53,
        value: 7,
        student_id: 3,
        task_id: 3,
      },
      {
        id: 54,
        value: 10,
        student_id: 3,
        task_id: 4,
      },
      {
        id: 55,
        value: 8,
        student_id: 3,
        task_id: 5,
      },
      {
        id: 56,
        value: 9,
        student_id: 3,
        task_id: 6,
      },
      {
        id: 57,
        value: 7,
        student_id: 3,
        task_id: 7,
      },
      {
        id: 58,
        value: 6,
        student_id: 3,
        task_id: 8,
      },
      {
        id: 59,
        value: 8,
        student_id: 3,
        task_id: 9,
      },
      {
        id: 60,
        value: 7,
        student_id: 3,
        task_id: 10,
      },
      {
        id: 61,
        value: 7,
        student_id: 3,
        task_id: 11,
      },
      {
        id: 62,
        value: 8,
        student_id: 3,
        task_id: 12,
      },
      {
        id: 63,
        value: 9,
        student_id: 3,
        task_id: 13,
      },
      {
        id: 64,
        value: 8,
        student_id: 3,
        task_id: 14,
      },
      {
        id: 65,
        value: 9,
        student_id: 3,
        task_id: 15,
      },
      {
        id: 66,
        value: 6,
        student_id: 3,
        task_id: 16,
      },
      {
        id: 67,
        value: 7,
        student_id: 3,
        task_id: 17,
      },
      {
        id: 68,
        value: 8,
        student_id: 3,
        task_id: 18,
      },
      {
        id: 69,
        value: 9,
        student_id: 3,
        task_id: 19,
      },
      {
        id: 70,
        value: 8,
        student_id: 3,
        task_id: 20,
      },
      {
        id: 71,
        value: 7,
        student_id: 3,
        task_id: 21,
      },
      {
        id: 72,
        value: 8,
        student_id: 3,
        task_id: 22,
      },
      {
        id: 73,
        value: 9,
        student_id: 3,
        task_id: 23,
      },
      {
        id: 74,
        value: 6,
        student_id: 3,
        task_id: 24,
      },
      {
        id: 75,
        value: 10,
        student_id: 3,
        task_id: 25,
      },
      //Леша
      {
        id: 76,
        value: 7,
        student_id: 4,
        task_id: 1,
      },
      {
        id: 77,
        value: 8,
        student_id: 4,
        task_id: 2,
      },
      {
        id: 78,
        value: 7,
        student_id: 4,
        task_id: 3,
      },
      {
        id: 79,
        value: 8,
        student_id: 4,
        task_id: 4,
      },
      {
        id: 80,
        value: 9,
        student_id: 4,
        task_id: 5,
      },
      {
        id: 81,
        value: 8,
        student_id: 4,
        task_id: 6,
      },
      {
        id: 82,
        value: 7,
        student_id: 4,
        task_id: 7,
      },
      {
        id: 83,
        value: 8,
        student_id: 4,
        task_id: 8,
      },
      {
        id: 84,
        value: 6,
        student_id: 4,
        task_id: 9,
      },
      {
        id: 85,
        value: 8,
        student_id: 4,
        task_id: 10,
      },
      {
        id: 86,
        value: 7,
        student_id: 4,
        task_id: 11,
      },
      {
        id: 87,
        value: 8,
        student_id: 4,
        task_id: 12,
      },
      {
        id: 88,
        value: 8,
        student_id: 4,
        task_id: 13,
      },
      {
        id: 89,
        value: 8,
        student_id: 4,
        task_id: 14,
      },
      {
        id: 90,
        value: 8,
        student_id: 4,
        task_id: 15,
      },
      {
        id: 91,
        value: 9,
        student_id: 4,
        task_id: 16,
      },
      {
        id: 92,
        value: 10,
        student_id: 4,
        task_id: 17,
      },
      {
        id: 93,
        value: 10,
        student_id: 4,
        task_id: 18,
      },
      {
        id: 94,
        value: 8,
        student_id: 4,
        task_id: 19,
      },
      {
        id: 95,
        value: 10,
        student_id: 4,
        task_id: 20,
      },
      {
        id: 96,
        value: 5,
        student_id: 4,
        task_id: 21,
      },
      {
        id: 97,
        value: 6,
        student_id: 4,
        task_id: 22,
      },
      {
        id: 98,
        value: 8,
        student_id: 4,
        task_id: 23,
      },
      {
        id: 99,
        value: 10,
        student_id: 4,
        task_id: 24,
      },
      {
        id: 100,
        value: 7,
        student_id: 4,
        task_id: 25,
      },
      //Артем
      {
        id: 101,
        value: 8,
        student_id: 5,
        task_id: 1,
      },
      {
        id: 102,
        value: 9,
        student_id: 5,
        task_id: 2,
      },
      {
        id: 103,
        value: 7,
        student_id: 5,
        task_id: 3,
      },
      {
        id: 104,
        value: 8,
        student_id: 5,
        task_id: 4,
      },
      {
        id: 105,
        value: 9,
        student_id: 5,
        task_id: 5,
      },
      {
        id: 106,
        value: 9,
        student_id: 5,
        task_id: 6,
      },
      {
        id: 107,
        value: 10,
        student_id: 5,
        task_id: 7,
      },
      {
        id: 108,
        value: 10,
        student_id: 5,
        task_id: 8,
      },
      {
        id: 109,
        value: 10,
        student_id: 5,
        task_id: 9,
      },
      {
        id: 110,
        value: 10,
        student_id: 5,
        task_id: 10,
      },
      {
        id: 111,
        value: 8,
        student_id: 5,
        task_id: 11,
      },
      {
        id: 112,
        value: 7,
        student_id: 5,
        task_id: 12,
      },
      {
        id: 113,
        value: 8,
        student_id: 5,
        task_id: 13,
      },
      {
        id: 114,
        value: 10,
        student_id: 5,
        task_id: 14,
      },
      {
        id: 115,
        value: 6,
        student_id: 5,
        task_id: 15,
      },
      {
        id: 116,
        value: 10,
        student_id: 5,
        task_id: 16,
      },
      {
        id: 117,
        value: 9,
        student_id: 5,
        task_id: 17,
      },
      {
        id: 118,
        value: 10,
        student_id: 5,
        task_id: 18,
      },
      {
        id: 119,
        value: 8,
        student_id: 5,
        task_id: 19,
      },
      {
        id: 120,
        value: 10,
        student_id: 5,
        task_id: 20,
      },
      {
        id: 121,
        value: 6,
        student_id: 5,
        task_id: 21,
      },
      {
        id: 122,
        value: 10,
        student_id: 5,
        task_id: 22,
      },
      {
        id: 123,
        value: 8,
        student_id: 5,
        task_id: 23,
      },
      {
        id: 124,
        value: 10,
        student_id: 5,
        task_id: 24,
      },
      {
        id: 125,
        value: 7,
        student_id: 5,
        task_id: 25,
      },
      //Илья
      {
        id: 126,
        value: 8,
        student_id: 6,
        task_id: 1,
      },
      {
        id: 127,
        value: 8,
        student_id: 6,
        task_id: 2,
      },
      {
        id: 128,
        value: 8,
        student_id: 6,
        task_id: 3,
      },
      {
        id: 129,
        value: 7,
        student_id: 6,
        task_id: 4,
      },
      {
        id: 130,
        value: 6,
        student_id: 6,
        task_id: 5,
      },
      {
        id: 131,
        value: 8,
        student_id: 6,
        task_id: 6,
      },
      {
        id: 132,
        value: 5,
        student_id: 6,
        task_id: 7,
      },
      {
        id: 133,
        value: 7,
        student_id: 6,
        task_id: 8,
      },
      {
        id: 134,
        value: 8,
        student_id: 6,
        task_id: 9,
      },
      {
        id: 135,
        value: 9,
        student_id: 6,
        task_id: 10,
      },
      {
        id: 136,
        value: 10,
        student_id: 6,
        task_id: 11,
      },
      {
        id: 137,
        value: 10,
        student_id: 6,
        task_id: 12,
      },
      {
        id: 138,
        value: 6,
        student_id: 6,
        task_id: 13,
      },
      {
        id: 139,
        value: 10,
        student_id: 6,
        task_id: 14,
      },
      {
        id: 140,
        value: 10,
        student_id: 6,
        task_id: 15,
      },
      {
        id: 141,
        value: 7,
        student_id: 6,
        task_id: 16,
      },
      {
        id: 142,
        value: 10,
        student_id: 6,
        task_id: 17,
      },
      {
        id: 143,
        value: 10,
        student_id: 6,
        task_id: 18,
      },
      {
        id: 144,
        value: 10,
        student_id: 6,
        task_id: 19,
      },
      {
        id: 145,
        value: 8,
        student_id: 6,
        task_id: 20,
      },
      {
        id: 146,
        value: 10,
        student_id: 6,
        task_id: 21,
      },
      {
        id: 147,
        value: 9,
        student_id: 6,
        task_id: 22,
      },
      {
        id: 148,
        value: 10,
        student_id: 6,
        task_id: 23,
      },
      {
        id: 149,
        value: 5,
        student_id: 6,
        task_id: 24,
      },
      {
        id: 150,
        value: 6,
        student_id: 6,
        task_id: 25,
      },
      //Антон
      {
        id: 151,
        value: 10,
        student_id: 7,
        task_id: 1,
      },
      {
        id: 152,
        value: 10,
        student_id: 7,
        task_id: 2,
      },
      {
        id: 153,
        value: 10,
        student_id: 7,
        task_id: 3,
      },
      {
        id: 154,
        value: 10,
        student_id: 7,
        task_id: 4,
      },
      {
        id: 155,
        value: 10,
        student_id: 7,
        task_id: 5,
      },
      {
        id: 156,
        value: 10,
        student_id: 7,
        task_id: 6,
      },
      {
        id: 157,
        value: 7,
        student_id: 7,
        task_id: 7,
      },
      {
        id: 158,
        value: 6,
        student_id: 7,
        task_id: 8,
      },
      {
        id: 159,
        value: 10,
        student_id: 7,
        task_id: 9,
      },
      {
        id: 160,
        value: 8,
        student_id: 7,
        task_id: 10,
      },
      {
        id: 161,
        value: 10,
        student_id: 7,
        task_id: 11,
      },
      {
        id: 162,
        value: 5,
        student_id: 7,
        task_id: 12,
      },
      {
        id: 163,
        value: 10,
        student_id: 7,
        task_id: 13,
      },
      {
        id: 164,
        value: 10,
        student_id: 7,
        task_id: 14,
      },
      {
        id: 165,
        value: 8,
        student_id: 7,
        task_id: 15,
      },
      {
        id: 166,
        value: 10,
        student_id: 7,
        task_id: 16,
      },
      {
        id: 167,
        value: 9,
        student_id: 7,
        task_id: 17,
      },
      {
        id: 168,
        value: 7,
        student_id: 7,
        task_id: 18,
      },
      {
        id: 169,
        value: 6,
        student_id: 7,
        task_id: 19,
      },
      {
        id: 170,
        value: 10,
        student_id: 7,
        task_id: 20,
      },
      {
        id: 171,
        value: 8,
        student_id: 7,
        task_id: 21,
      },
      {
        id: 172,
        value: 10,
        student_id: 7,
        task_id: 22,
      },
      {
        id: 173,
        value: 9,
        student_id: 7,
        task_id: 23,
      },
      {
        id: 174,
        value: 10,
        student_id: 7,
        task_id: 24,
      },
      {
        id: 175,
        value: 9,
        student_id: 7,
        task_id: 25,
      },
      //Коля
      {
        id: 176,
        value: 7,
        student_id: 8,
        task_id: 1,
      },
      {
        id: 177,
        value: 8,
        student_id: 8,
        task_id: 2,
      },
      {
        id: 178,
        value: 6,
        student_id: 8,
        task_id: 3,
      },
      {
        id: 179,
        value: 10,
        student_id: 8,
        task_id: 4,
      },
      {
        id: 180,
        value: 10,
        student_id: 8,
        task_id: 5,
      },
      {
        id: 181,
        value: 10,
        student_id: 8,
        task_id: 6,
      },
      {
        id: 182,
        value: 8,
        student_id: 8,
        task_id: 7,
      },
      {
        id: 183,
        value: 10,
        student_id: 8,
        task_id: 8,
      },
      {
        id: 184,
        value: 7,
        student_id: 8,
        task_id: 9,
      },
      {
        id: 185,
        value: 10,
        student_id: 8,
        task_id: 10,
      },
      {
        id: 186,
        value: 9,
        student_id: 8,
        task_id: 11,
      },
      {
        id: 187,
        value: 10,
        student_id: 8,
        task_id: 12,
      },
      {
        id: 188,
        value: 8,
        student_id: 8,
        task_id: 13,
      },
      {
        id: 189,
        value: 10,
        student_id: 8,
        task_id: 14,
      },
      {
        id: 190,
        value: 6,
        student_id: 8,
        task_id: 15,
      },
      {
        id: 191,
        value: 10,
        student_id: 8,
        task_id: 16,
      },
      {
        id: 192,
        value: 7,
        student_id: 8,
        task_id: 17,
      },
      {
        id: 193,
        value: 10,
        student_id: 8,
        task_id: 18,
      },
      {
        id: 194,
        value: 8,
        student_id: 8,
        task_id: 19,
      },
      {
        id: 195,
        value: 10,
        student_id: 8,
        task_id: 20,
      },
      {
        id: 196,
        value: 5,
        student_id: 8,
        task_id: 21,
      },
      {
        id: 197,
        value: 10,
        student_id: 8,
        task_id: 22,
      },
      {
        id: 198,
        value: 10,
        student_id: 8,
        task_id: 23,
      },
      {
        id: 199,
        value: 6,
        student_id: 8,
        task_id: 24,
      },
      {
        id: 200,
        value: 8,
        student_id: 8,
        task_id: 25,
      },
      //Женя Скрага
      {
        id: 201,
        value: 10,
        student_id: 9,
        task_id: 1,
      },
      {
        id: 202,
        value: 9,
        student_id: 9,
        task_id: 2,
      },
      {
        id: 203,
        value: 7,
        student_id: 9,
        task_id: 3,
      },
      {
        id: 204,
        value: 8,
        student_id: 9,
        task_id: 4,
      },
      {
        id: 205,
        value: 10,
        student_id: 9,
        task_id: 5,
      },
      {
        id: 206,
        value: 9,
        student_id: 9,
        task_id: 6,
      },
      {
        id: 207,
        value: 10,
        student_id: 9,
        task_id: 7,
      },
      {
        id: 208,
        value: 10,
        student_id: 9,
        task_id: 8,
      },
      {
        id: 209,
        value: 10,
        student_id: 9,
        task_id: 9,
      },
      {
        id: 210,
        value: 5,
        student_id: 9,
        task_id: 10,
      },
      {
        id: 211,
        value: 5,
        student_id: 9,
        task_id: 11,
      },
      {
        id: 212,
        value: 5,
        student_id: 9,
        task_id: 12,
      },
      {
        id: 213,
        value: 6,
        student_id: 9,
        task_id: 13,
      },
      {
        id: 214,
        value: 7,
        student_id: 9,
        task_id: 14,
      },
      {
        id: 215,
        value: 10,
        student_id: 9,
        task_id: 15,
      },
      {
        id: 216,
        value: 4,
        student_id: 9,
        task_id: 16,
      },
      {
        id: 217,
        value: 4,
        student_id: 9,
        task_id: 17,
      },
      {
        id: 218,
        value: 6,
        student_id: 9,
        task_id: 18,
      },
      {
        id: 219,
        value: 8,
        student_id: 9,
        task_id: 19,
      },
      {
        id: 220,
        value: 9,
        student_id: 9,
        task_id: 20,
      },
      {
        id: 221,
        value: 10,
        student_id: 9,
        task_id: 21,
      },
      {
        id: 222,
        value: 10,
        student_id: 9,
        task_id: 22,
      },
      {
        id: 223,
        value: 10,
        student_id: 9,
        task_id: 23,
      },
      {
        id: 224,
        value: 8,
        student_id: 9,
        task_id: 24,
      },
      {
        id: 225,
        value: 7,
        student_id: 9,
        task_id: 25,
      },
      //Вика
      {
        id: 226,
        value: 7,
        student_id: 10,
        task_id: 1,
      },
      {
        id: 227,
        value: 10,
        student_id: 10,
        task_id: 2,
      },
      {
        id: 228,
        value: 10,
        student_id: 10,
        task_id: 3,
      },
      {
        id: 229,
        value: 8,
        student_id: 10,
        task_id: 4,
      },
      {
        id: 230,
        value: 10,
        student_id: 10,
        task_id: 5,
      },
      {
        id: 231,
        value: 6,
        student_id: 10,
        task_id: 6,
      },
      {
        id: 232,
        value: 10,
        student_id: 10,
        task_id: 7,
      },
      {
        id: 233,
        value: 8,
        student_id: 10,
        task_id: 8,
      },
      {
        id: 234,
        value: 9,
        student_id: 10,
        task_id: 9,
      },
      {
        id: 235,
        value: 10,
        student_id: 10,
        task_id: 10,
      },
      {
        id: 236,
        value: 7,
        student_id: 10,
        task_id: 11,
      },
      {
        id: 237,
        value: 10,
        student_id: 10,
        task_id: 12,
      },
      {
        id: 238,
        value: 10,
        student_id: 10,
        task_id: 13,
      },
      {
        id: 239,
        value: 8,
        student_id: 10,
        task_id: 14,
      },
      {
        id: 240,
        value: 10,
        student_id: 10,
        task_id: 15,
      },
      {
        id: 241,
        value: 10,
        student_id: 10,
        task_id: 16,
      },
      {
        id: 242,
        value: 6,
        student_id: 10,
        task_id: 17,
      },
      {
        id: 243,
        value: 8,
        student_id: 10,
        task_id: 18,
      },
      {
        id: 244,
        value: 7,
        student_id: 10,
        task_id: 19,
      },
      {
        id: 245,
        value: 10,
        student_id: 10,
        task_id: 20,
      },
      {
        id: 246,
        value: 5,
        student_id: 10,
        task_id: 21,
      },
      {
        id: 247,
        value: 6,
        student_id: 10,
        task_id: 22,
      },
      {
        id: 248,
        value: 7,
        student_id: 10,
        task_id: 23,
      },
      {
        id: 249,
        value: 4,
        student_id: 10,
        task_id: 24,
      },
      {
        id: 250,
        value: 4,
        student_id: 10,
        task_id: 25,
      },
      //Паша
      {
        id: 251,
        value: 7,
        student_id: 11,
        task_id: 1,
      },
      {
        id: 252,
        value: 7,
        student_id: 11,
        task_id: 2,
      },
      {
        id: 253,
        value: 7,
        student_id: 11,
        task_id: 3,
      },
      {
        id: 254,
        value: 7,
        student_id: 11,
        task_id: 4,
      },
      {
        id: 255,
        value: 8,
        student_id: 11,
        task_id: 5,
      },
      {
        id: 256,
        value: 9,
        student_id: 11,
        task_id: 6,
      },
      {
        id: 257,
        value: 6,
        student_id: 11,
        task_id: 7,
      },
      {
        id: 258,
        value: 9,
        student_id: 11,
        task_id: 8,
      },
      {
        id: 259,
        value: 7,
        student_id: 11,
        task_id: 9,
      },
      {
        id: 260,
        value: 8,
        student_id: 11,
        task_id: 10,
      },
      {
        id: 261,
        value: 9,
        student_id: 11,
        task_id: 11,
      },
      {
        id: 262,
        value: 6,
        student_id: 11,
        task_id: 12,
      },
      {
        id: 263,
        value: 5,
        student_id: 11,
        task_id: 13,
      },
      {
        id: 264,
        value: 7,
        student_id: 11,
        task_id: 14,
      },
      {
        id: 265,
        value: 8,
        student_id: 11,
        task_id: 15,
      },
      {
        id: 266,
        value: 9,
        student_id: 11,
        task_id: 16,
      },
      {
        id: 267,
        value: 10,
        student_id: 11,
        task_id: 17,
      },
      {
        id: 268,
        value: 10,
        student_id: 11,
        task_id: 18,
      },
      {
        id: 269,
        value: 8,
        student_id: 11,
        task_id: 19,
      },
      {
        id: 270,
        value: 6,
        student_id: 11,
        task_id: 20,
      },
      {
        id: 271,
        value: 6,
        student_id: 11,
        task_id: 21,
      },
      {
        id: 272,
        value: 6,
        student_id: 11,
        task_id: 22,
      },
      {
        id: 273,
        value: 7,
        student_id: 11,
        task_id: 23,
      },
      {
        id: 274,
        value: 10,
        student_id: 11,
        task_id: 24,
      },
      {
        id: 275,
        value: 8,
        student_id: 11,
        task_id: 25,
      },
      //Саша
      {
        id: 276,
        value: 5,
        student_id: 12,
        task_id: 1,
      },
      {
        id: 277,
        value: 6,
        student_id: 12,
        task_id: 2,
      },
      {
        id: 278,
        value: 6,
        student_id: 12,
        task_id: 3,
      },
      {
        id: 279,
        value: 7,
        student_id: 12,
        task_id: 4,
      },
      {
        id: 280,
        value: 8,
        student_id: 12,
        task_id: 5,
      },
      {
        id: 281,
        value: 9,
        student_id: 12,
        task_id: 6,
      },
      {
        id: 282,
        value: 8,
        student_id: 12,
        task_id: 7,
      },
      {
        id: 283,
        value: 9,
        student_id: 12,
        task_id: 8,
      },
      {
        id: 284,
        value: 10,
        student_id: 12,
        task_id: 9,
      },
      {
        id: 285,
        value: 9,
        student_id: 12,
        task_id: 10,
      },
      {
        id: 286,
        value: 10,
        student_id: 12,
        task_id: 11,
      },
      {
        id: 287,
        value: 10,
        student_id: 12,
        task_id: 12,
      },
      {
        id: 288,
        value: 10,
        student_id: 12,
        task_id: 13,
      },
      {
        id: 289,
        value: 9,
        student_id: 12,
        task_id: 14,
      },
      {
        id: 290,
        value: 10,
        student_id: 12,
        task_id: 15,
      },
      {
        id: 291,
        value: 6,
        student_id: 12,
        task_id: 16,
      },
      {
        id: 292,
        value: 7,
        student_id: 12,
        task_id: 17,
      },
      {
        id: 293,
        value: 8,
        student_id: 12,
        task_id: 18,
      },
      {
        id: 294,
        value: 9,
        student_id: 12,
        task_id: 19,
      },
      {
        id: 295,
        value: 10,
        student_id: 12,
        task_id: 20,
      },
      {
        id: 296,
        value: 7,
        student_id: 12,
        task_id: 21,
      },
      {
        id: 297,
        value: 6,
        student_id: 12,
        task_id: 22,
      },
      {
        id: 298,
        value: 8,
        student_id: 12,
        task_id: 23,
      },
      {
        id: 299,
        value: 8,
        student_id: 12,
        task_id: 24,
      },
      {
        id: 300,
        value: 9,
        student_id: 12,
        task_id: 25,
      },
      //Федя
      {
        id: 301,
        value: 6,
        student_id: 13,
        task_id: 1,
      },
      {
        id: 302,
        value: 7,
        student_id: 13,
        task_id: 2,
      },
      {
        id: 303,
        value: 6,
        student_id: 13,
        task_id: 3,
      },
      {
        id: 304,
        value: 5,
        student_id: 13,
        task_id: 4,
      },
      {
        id: 305,
        value: 5,
        student_id: 13,
        task_id: 5,
      },
      {
        id: 306,
        value: 6,
        student_id: 13,
        task_id: 6,
      },
      {
        id: 307,
        value: 7,
        student_id: 13,
        task_id: 7,
      },
      {
        id: 308,
        value: 8,
        student_id: 13,
        task_id: 8,
      },
      {
        id: 309,
        value: 7,
        student_id: 13,
        task_id: 9,
      },
      {
        id: 310,
        value: 6,
        student_id: 13,
        task_id: 10,
      },
      {
        id: 311,
        value: 8,
        student_id: 13,
        task_id: 11,
      },
      {
        id: 312,
        value: 8,
        student_id: 13,
        task_id: 12,
      },
      {
        id: 313,
        value: 7,
        student_id: 13,
        task_id: 13,
      },
      {
        id: 314,
        value: 7,
        student_id: 13,
        task_id: 14,
      },
      {
        id: 315,
        value: 6,
        student_id: 13,
        task_id: 15,
      },
      {
        id: 316,
        value: 7,
        student_id: 13,
        task_id: 16,
      },
      {
        id: 317,
        value: 8,
        student_id: 13,
        task_id: 17,
      },
      {
        id: 318,
        value: 7,
        student_id: 13,
        task_id: 18,
      },
      {
        id: 319,
        value: 8,
        student_id: 13,
        task_id: 19,
      },
      {
        id: 320,
        value: 6,
        student_id: 13,
        task_id: 20,
      },
      {
        id: 321,
        value: 7,
        student_id: 13,
        task_id: 21,
      },
      {
        id: 322,
        value: 7,
        student_id: 13,
        task_id: 22,
      },
      {
        id: 323,
        value: 8,
        student_id: 13,
        task_id: 23,
      },
      {
        id: 324,
        value: 5,
        student_id: 13,
        task_id: 24,
      },
      {
        id: 325,
        value: 7,
        student_id: 13,
        task_id: 25,
      },
      //Женя Шарко
      {
        id: 326,
        value: 6,
        student_id: 14,
        task_id: 1,
      },
      {
        id: 327,
        value: 7,
        student_id: 14,
        task_id: 2,
      },
      {
        id: 328,
        value: 7,
        student_id: 14,
        task_id: 3,
      },
      {
        id: 329,
        value: 7,
        student_id: 14,
        task_id: 4,
      },
      {
        id: 330,
        value: 5,
        student_id: 14,
        task_id: 5,
      },
      {
        id: 331,
        value: 6,
        student_id: 14,
        task_id: 6,
      },
      {
        id: 332,
        value: 8,
        student_id: 14,
        task_id: 7,
      },
      {
        id: 333,
        value: 5,
        student_id: 14,
        task_id: 8,
      },
      {
        id: 334,
        value: 6,
        student_id: 14,
        task_id: 9,
      },
      {
        id: 335,
        value: 7,
        student_id: 14,
        task_id: 10,
      },
      {
        id: 336,
        value: 5,
        student_id: 14,
        task_id: 11,
      },
      {
        id: 337,
        value: 8,
        student_id: 14,
        task_id: 12,
      },
      {
        id: 338,
        value: 6,
        student_id: 14,
        task_id: 13,
      },
      {
        id: 339,
        value: 4,
        student_id: 14,
        task_id: 14,
      },
      {
        id: 340,
        value: 4,
        student_id: 14,
        task_id: 15,
      },
      {
        id: 341,
        value: 4,
        student_id: 14,
        task_id: 16,
      },
      {
        id: 342,
        value: 4,
        student_id: 14,
        task_id: 17,
      },
      {
        id: 343,
        value: 5,
        student_id: 14,
        task_id: 18,
      },
      {
        id: 344,
        value: 6,
        student_id: 14,
        task_id: 19,
      },
      {
        id: 345,
        value: 6,
        student_id: 14,
        task_id: 20,
      },
      {
        id: 346,
        value: 10,
        student_id: 14,
        task_id: 21,
      },
      {
        id: 347,
        value: 6,
        student_id: 14,
        task_id: 22,
      },
      {
        id: 348,
        value: 6,
        student_id: 14,
        task_id: 23,
      },
      {
        id: 349,
        value: 4,
        student_id: 14,
        task_id: 24,
      },
      {
        id: 350,
        value: 10,
        student_id: 14,
        task_id: 25,
      },
      //Доморад Никита
      {
        id: 351,
        value: 5,
        student_id: 15,
        task_id: 1,
      },
      {
        id: 352,
        value: 5,
        student_id: 15,
        task_id: 2,
      },
      {
        id: 353,
        value: 5,
        student_id: 15,
        task_id: 3,
      },
      {
        id: 354,
        value: 5,
        student_id: 15,
        task_id: 4,
      },
      {
        id: 355,
        value: 5,
        student_id: 15,
        task_id: 5,
      },
      {
        id: 356,
        value: 5,
        student_id: 15,
        task_id: 6,
      },
      {
        id: 357,
        value: 5,
        student_id: 15,
        task_id: 7,
      },
      {
        id: 358,
        value: 5,
        student_id: 15,
        task_id: 8,
      },
      {
        id: 359,
        value: 6,
        student_id: 15,
        task_id: 9,
      },
      {
        id: 360,
        value: 7,
        student_id: 15,
        task_id: 10,
      },
      {
        id: 361,
        value: 6,
        student_id: 15,
        task_id: 11,
      },
      {
        id: 362,
        value: 10,
        student_id: 15,
        task_id: 12,
      },
      {
        id: 363,
        value: 10,
        student_id: 15,
        task_id: 13,
      },
      {
        id: 364,
        value: 5,
        student_id: 15,
        task_id: 14,
      },
      {
        id: 365,
        value: 10,
        student_id: 15,
        task_id: 15,
      },
      {
        id: 366,
        value: 6,
        student_id: 15,
        task_id: 16,
      },
      {
        id: 367,
        value: 7,
        student_id: 15,
        task_id: 17,
      },
      {
        id: 368,
        value: 10,
        student_id: 15,
        task_id: 18,
      },
      {
        id: 369,
        value: 7,
        student_id: 15,
        task_id: 19,
      },
      {
        id: 370,
        value: 7,
        student_id: 15,
        task_id: 20,
      },
      {
        id: 371,
        value: 5,
        student_id: 15,
        task_id: 21,
      },
      {
        id: 372,
        value: 6,
        student_id: 15,
        task_id: 22,
      },
      {
        id: 373,
        value: 4,
        student_id: 15,
        task_id: 23,
      },
      {
        id: 374,
        value: 6,
        student_id: 15,
        task_id: 24,
      },
      {
        id: 375,
        value: 5,
        student_id: 15,
        task_id: 25,
      },
      //Денис
      {
        id: 376,
        value: 7,
        student_id: 16,
        task_id: 1,
      },
      {
        id: 377,
        value: 6,
        student_id: 16,
        task_id: 2,
      },
      {
        id: 378,
        value: 6,
        student_id: 16,
        task_id: 3,
      },
      {
        id: 379,
        value: 6,
        student_id: 16,
        task_id: 4,
      },
      {
        id: 380,
        value: 7,
        student_id: 16,
        task_id: 5,
      },
      {
        id: 381,
        value: 6,
        student_id: 16,
        task_id: 6,
      },
      {
        id: 382,
        value: 6,
        student_id: 16,
        task_id: 7,
      },
      {
        id: 383,
        value: 6,
        student_id: 16,
        task_id: 8,
      },
      {
        id: 384,
        value: 6,
        student_id: 16,
        task_id: 9,
      },
      {
        id: 385,
        value: 4,
        student_id: 16,
        task_id: 10,
      },
      {
        id: 386,
        value: 6,
        student_id: 16,
        task_id: 11,
      },
      {
        id: 387,
        value: 6,
        student_id: 16,
        task_id: 12,
      },
      {
        id: 388,
        value: 6,
        student_id: 16,
        task_id: 13,
      },
      {
        id: 389,
        value: 6,
        student_id: 16,
        task_id: 14,
      },
      {
        id: 390,
        value: 6,
        student_id: 16,
        task_id: 15,
      },
      {
        id: 391,
        value: 8,
        student_id: 16,
        task_id: 16,
      },
      {
        id: 392,
        value: 6,
        student_id: 16,
        task_id: 17,
      },
      {
        id: 393,
        value: 8,
        student_id: 16,
        task_id: 18,
      },
      {
        id: 394,
        value: 6,
        student_id: 16,
        task_id: 19,
      },
      {
        id: 395,
        value: 6,
        student_id: 16,
        task_id: 20,
      },
      {
        id: 396,
        value: 4,
        student_id: 16,
        task_id: 21,
      },
      {
        id: 397,
        value: 6,
        student_id: 16,
        task_id: 22,
      },
      {
        id: 398,
        value: 7,
        student_id: 16,
        task_id: 23,
      },
      {
        id: 399,
        value: 5,
        student_id: 16,
        task_id: 24,
      },
      {
        id: 400,
        value: 7,
        student_id: 16,
        task_id: 25,
      },
      //Влад
      {
        id: 401,
        value: 6,
        student_id: 17,
        task_id: 1,
      },
      {
        id: 402,
        value: 6,
        student_id: 17,
        task_id: 2,
      },
      {
        id: 403,
        value: 6,
        student_id: 17,
        task_id: 3,
      },
      {
        id: 404,
        value: 6,
        student_id: 17,
        task_id: 4,
      },
      {
        id: 405,
        value: 6,
        student_id: 17,
        task_id: 5,
      },
      {
        id: 406,
        value: 4,
        student_id: 17,
        task_id: 6,
      },
      {
        id: 407,
        value: 6,
        student_id: 17,
        task_id: 7,
      },
      {
        id: 408,
        value: 6,
        student_id: 17,
        task_id: 8,
      },
      {
        id: 409,
        value: 4,
        student_id: 17,
        task_id: 9,
      },
      {
        id: 410,
        value: 4,
        student_id: 17,
        task_id: 10,
      },
      {
        id: 411,
        value: 6,
        student_id: 17,
        task_id: 11,
      },
      {
        id: 412,
        value: 6,
        student_id: 17,
        task_id: 12,
      },
      {
        id: 413,
        value: 5,
        student_id: 17,
        task_id: 13,
      },
      {
        id: 414,
        value: 6,
        student_id: 17,
        task_id: 14,
      },
      {
        id: 415,
        value: 6,
        student_id: 17,
        task_id: 15,
      },
      {
        id: 416,
        value: 6,
        student_id: 17,
        task_id: 16,
      },
      {
        id: 417,
        value: 6,
        student_id: 17,
        task_id: 17,
      },
      {
        id: 418,
        value: 7,
        student_id: 17,
        task_id: 18,
      },
      {
        id: 419,
        value: 6,
        student_id: 17,
        task_id: 19,
      },
      {
        id: 420,
        value: 9,
        student_id: 17,
        task_id: 20,
      },
      {
        id: 421,
        value: 6,
        student_id: 17,
        task_id: 21,
      },
      {
        id: 422,
        value: 6,
        student_id: 17,
        task_id: 22,
      },
      {
        id: 423,
        value: 4,
        student_id: 17,
        task_id: 23,
      },
      {
        id: 424,
        value: 6,
        student_id: 17,
        task_id: 24,
      },
      {
        id: 425,
        value: 4,
        student_id: 17,
        task_id: 25,
      },
      //Глеб
      {
        id: 426,
        value: 5,
        student_id: 18,
        task_id: 1,
      },
      {
        id: 427,
        value: 5,
        student_id: 18,
        task_id: 2,
      },
      {
        id: 428,
        value: 5,
        student_id: 18,
        task_id: 3,
      },
      {
        id: 429,
        value: 5,
        student_id: 18,
        task_id: 4,
      },
      {
        id: 430,
        value: 5,
        student_id: 18,
        task_id: 5,
      },
      {
        id: 431,
        value: 5,
        student_id: 18,
        task_id: 6,
      },
      {
        id: 432,
        value: 5,
        student_id: 18,
        task_id: 7,
      },
      {
        id: 433,
        value: 5,
        student_id: 18,
        task_id: 8,
      },
      {
        id: 434,
        value: 5,
        student_id: 18,
        task_id: 9,
      },
      {
        id: 435,
        value: 5,
        student_id: 18,
        task_id: 10,
      },
      {
        id: 436,
        value: 5,
        student_id: 18,
        task_id: 11,
      },
      {
        id: 437,
        value: 5,
        student_id: 18,
        task_id: 12,
      },
      {
        id: 438,
        value: 5,
        student_id: 18,
        task_id: 13,
      },
      {
        id: 439,
        value: 5,
        student_id: 18,
        task_id: 14,
      },
      {
        id: 440,
        value: 5,
        student_id: 18,
        task_id: 15,
      },
      {
        id: 441,
        value: 5,
        student_id: 18,
        task_id: 16,
      },
      {
        id: 442,
        value: 5,
        student_id: 18,
        task_id: 17,
      },
      {
        id: 443,
        value: 5,
        student_id: 18,
        task_id: 18,
      },
      {
        id: 444,
        value: 5,
        student_id: 18,
        task_id: 19,
      },
      {
        id: 445,
        value: 5,
        student_id: 18,
        task_id: 20,
      },
      {
        id: 446,
        value: 5,
        student_id: 18,
        task_id: 21,
      },
      {
        id: 447,
        value: 5,
        student_id: 18,
        task_id: 22,
      },
      {
        id: 448,
        value: 5,
        student_id: 18,
        task_id: 23,
      },
      {
        id: 449,
        value: 5,
        student_id: 18,
        task_id: 24,
      },
      {
        id: 450,
        value: 5,
        student_id: 18,
        task_id: 25,
      },
      //Дима
      {
        id: 451,
        value: 4,
        student_id: 19,
        task_id: 1,
      },
      {
        id: 452,
        value: 4,
        student_id: 19,
        task_id: 2,
      },
      {
        id: 453,
        value: 4,
        student_id: 19,
        task_id: 3,
      },
      {
        id: 454,
        value: 4,
        student_id: 19,
        task_id: 4,
      },
      {
        id: 455,
        value: 4,
        student_id: 19,
        task_id: 5,
      },
      {
        id: 456,
        value: 4,
        student_id: 19,
        task_id: 6,
      },
      {
        id: 457,
        value: 4,
        student_id: 19,
        task_id: 7,
      },
      {
        id: 458,
        value: 4,
        student_id: 19,
        task_id: 8,
      },
      {
        id: 459,
        value: 4,
        student_id: 19,
        task_id: 9,
      },
      {
        id: 460,
        value: 4,
        student_id: 19,
        task_id: 10,
      },
      {
        id: 461,
        value: 4,
        student_id: 19,
        task_id: 11,
      },
      {
        id: 462,
        value: 4,
        student_id: 19,
        task_id: 12,
      },
      {
        id: 463,
        value: 4,
        student_id: 19,
        task_id: 13,
      },
      {
        id: 464,
        value: 4,
        student_id: 19,
        task_id: 14,
      },
      {
        id: 465,
        value: 4,
        student_id: 19,
        task_id: 15,
      },
      {
        id: 466,
        value: 4,
        student_id: 19,
        task_id: 16,
      },
      {
        id: 467,
        value: 4,
        student_id: 19,
        task_id: 17,
      },
      {
        id: 468,
        value: 4,
        student_id: 19,
        task_id: 18,
      },
      {
        id: 469,
        value: 4,
        student_id: 19,
        task_id: 19,
      },
      {
        id: 470,
        value: 4,
        student_id: 19,
        task_id: 20,
      },
      {
        id: 471,
        value: 4,
        student_id: 19,
        task_id: 21,
      },
      {
        id: 472,
        value: 4,
        student_id: 19,
        task_id: 22,
      },
      {
        id: 473,
        value: 4,
        student_id: 19,
        task_id: 23,
      },
      {
        id: 474,
        value: 4,
        student_id: 19,
        task_id: 24,
      },
      {
        id: 475,
        value: 4,
        student_id: 19,
        task_id: 25,
      },
      //Ваня
      {
        id: 476,
        value: 4,
        student_id: 20,
        task_id: 1,
      },
      {
        id: 477,
        value: 4,
        student_id: 20,
        task_id: 2,
      },
      {
        id: 478,
        value: 4,
        student_id: 20,
        task_id: 3,
      },
      {
        id: 479,
        value: 4,
        student_id: 20,
        task_id: 4,
      },
      {
        id: 480,
        value: 4,
        student_id: 20,
        task_id: 5,
      },
      {
        id: 481,
        value: 4,
        student_id: 20,
        task_id: 6,
      },
      {
        id: 482,
        value: 4,
        student_id: 20,
        task_id: 7,
      },
      {
        id: 483,
        value: 4,
        student_id: 20,
        task_id: 8,
      },
      {
        id: 484,
        value: 4,
        student_id: 20,
        task_id: 9,
      },
      {
        id: 485,
        value: 4,
        student_id: 20,
        task_id: 10,
      },
      {
        id: 486,
        value: 4,
        student_id: 20,
        task_id: 11,
      },
      {
        id: 487,
        value: 4,
        student_id: 20,
        task_id: 12,
      },
      {
        id: 488,
        value: 4,
        student_id: 20,
        task_id: 13,
      },
      {
        id: 489,
        value: 4,
        student_id: 20,
        task_id: 14,
      },
      {
        id: 490,
        value: 4,
        student_id: 20,
        task_id: 15,
      },
      {
        id: 491,
        value: 4,
        student_id: 20,
        task_id: 16,
      },
      {
        id: 492,
        value: 4,
        student_id: 20,
        task_id: 17,
      },
      {
        id: 493,
        value: 4,
        student_id: 20,
        task_id: 18,
      },
      {
        id: 494,
        value: 4,
        student_id: 20,
        task_id: 19,
      },
      {
        id: 495,
        value: 4,
        student_id: 20,
        task_id: 20,
      },
      {
        id: 496,
        value: 4,
        student_id: 20,
        task_id: 21,
      },
      //Москалев Миша
      {
        id: 497,
        value: 4,
        student_id: 21,
        task_id: 1,
      },
      {
        id: 498,
        value: 4,
        student_id: 21,
        task_id: 2,
      },
      {
        id: 499,
        value: 4,
        student_id: 21,
        task_id: 3,
      },
      {
        id: 500,
        value: 4,
        student_id: 21,
        task_id: 4,
      },
      {
        id: 501,
        value: 4,
        student_id: 21,
        task_id: 5,
      },
      {
        id: 502,
        value: 4,
        student_id: 21,
        task_id: 6,
      },
      {
        id: 503,
        value: 4,
        student_id: 21,
        task_id: 7,
      },
      {
        id: 504,
        value: 4,
        student_id: 21,
        task_id: 8,
      },
      {
        id: 505,
        value: 4,
        student_id: 21,
        task_id: 9,
      },
      {
        id: 506,
        value: 4,
        student_id: 21,
        task_id: 10,
      },
      {
        id: 507,
        value: 4,
        student_id: 21,
        task_id: 11,
      },
      {
        id: 508,
        value: 4,
        student_id: 21,
        task_id: 12,
      },
      {
        id: 509,
        value: 4,
        student_id: 21,
        task_id: 13,
      },
      {
        id: 510,
        value: 4,
        student_id: 21,
        task_id: 14,
      },
      {
        id: 511,
        value: 4,
        student_id: 21,
        task_id: 15,
      },
      {
        id: 512,
        value: 4,
        student_id: 21,
        task_id: 16,
      },
      {
        id: 513,
        value: 4,
        student_id: 21,
        task_id: 17,
      },
      {
        id: 514,
        value: 4,
        student_id: 21,
        task_id: 18,
      },
      {
        id: 515,
        value: 4,
        student_id: 21,
        task_id: 19,
      },
      {
        id: 516,
        value: 4,
        student_id: 21,
        task_id: 20,
      },
      {
        id: 517,
        value: 4,
        student_id: 21,
        task_id: 21,
      },
      {
        id: 518,
        value: 4,
        student_id: 21,
        task_id: 22,
      },
      {
        id: 519,
        value: 4,
        student_id: 21,
        task_id: 23,
      },
      {
        id: 520,
        value: 4,
        student_id: 21,
        task_id: 24,
      },
      {
        id: 521,
        value: 4,
        student_id: 21,
        task_id: 25,
      },
      //Радик
      {
        id: 522,
        value: 4,
        student_id: 22,
        task_id: 1,
      },
      {
        id: 523,
        value: 4,
        student_id: 22,
        task_id: 2,
      },
      {
        id: 524,
        value: 4,
        student_id: 22,
        task_id: 3,
      },
      {
        id: 525,
        value: 4,
        student_id: 22,
        task_id: 4,
      },
      {
        id: 526,
        value: 4,
        student_id: 22,
        task_id: 5,
      },
      {
        id: 527,
        value: 4,
        student_id: 22,
        task_id: 6,
      },
      {
        id: 528,
        value: 4,
        student_id: 22,
        task_id: 7,
      },
      {
        id: 529,
        value: 4,
        student_id: 22,
        task_id: 8,
      },
      {
        id: 530,
        value: 4,
        student_id: 22,
        task_id: 9,
      },
      {
        id: 531,
        value: 4,
        student_id: 22,
        task_id: 10,
      },
      {
        id: 532,
        value: 4,
        student_id: 22,
        task_id: 11,
      },
      {
        id: 533,
        value: 4,
        student_id: 22,
        task_id: 12,
      },
      {
        id: 534,
        value: 4,
        student_id: 22,
        task_id: 13,
      },
      {
        id: 535,
        value: 4,
        student_id: 22,
        task_id: 14,
      },
      {
        id: 536,
        value: 4,
        student_id: 22,
        task_id: 15,
      },
      {
        id: 537,
        value: 4,
        student_id: 22,
        task_id: 16,
      },
      {
        id: 538,
        value: 4,
        student_id: 22,
        task_id: 17,
      },
      {
        id: 539,
        value: 4,
        student_id: 22,
        task_id: 18,
      },
      {
        id: 540,
        value: 4,
        student_id: 22,
        task_id: 19,
      },
      //Кристина
      {
        id: 541,
        value: 4,
        student_id: 23,
        task_id: 1,
      },
      {
        id: 542,
        value: 4,
        student_id: 23,
        task_id: 2,
      },
      {
        id: 543,
        value: 4,
        student_id: 23,
        task_id: 3,
      },
      {
        id: 544,
        value: 4,
        student_id: 23,
        task_id: 4,
      },
      {
        id: 545,
        value: 4,
        student_id: 23,
        task_id: 5,
      },
      {
        id: 546,
        value: 4,
        student_id: 23,
        task_id: 6,
      },
      {
        id: 547,
        value: 4,
        student_id: 23,
        task_id: 7,
      },
      {
        id: 548,
        value: 4,
        student_id: 23,
        task_id: 8,
      },
      {
        id: 549,
        value: 4,
        student_id: 23,
        task_id: 9,
      },
      {
        id: 550,
        value: 4,
        student_id: 23,
        task_id: 10,
      },
      {
        id: 551,
        value: 4,
        student_id: 23,
        task_id: 11,
      },
      {
        id: 552,
        value: 4,
        student_id: 23,
        task_id: 12,
      },
      {
        id: 553,
        value: 4,
        student_id: 23,
        task_id: 13,
      },
      {
        id: 554,
        value: 4,
        student_id: 23,
        task_id: 14,
      },
      {
        id: 555,
        value: 4,
        student_id: 23,
        task_id: 15,
      },
      {
        id: 556,
        value: 4,
        student_id: 23,
        task_id: 16,
      },
      {
        id: 557,
        value: 4,
        student_id: 23,
        task_id: 17,
      },
      {
        id: 558,
        value: 4,
        student_id: 23,
        task_id: 18,
      },
      {
        id: 559,
        value: 4,
        student_id: 23,
        task_id: 19,
      },
      {
        id: 560,
        value: 4,
        student_id: 23,
        task_id: 20,
      },
      {
        id: 561,
        value: 4,
        student_id: 23,
        task_id: 21,
      },
      {
        id: 562,
        value: 4,
        student_id: 23,
        task_id: 22,
      },
      {
        id: 563,
        value: 4,
        student_id: 23,
        task_id: 23,
      },
      {
        id: 564,
        value: 4,
        student_id: 23,
        task_id: 24,
      },
      {
        id: 565,
        value: 4,
        student_id: 23,
        task_id: 25,
      },
      //Назарья
      {
        id: 566,
        value: 4,
        student_id: 24,
        task_id: 1,
      },
      {
        id: 567,
        value: 4,
        student_id: 24,
        task_id: 2,
      },
      {
        id: 568,
        value: 4,
        student_id: 24,
        task_id: 3,
      },
      {
        id: 569,
        value: 4,
        student_id: 24,
        task_id: 4,
      },
      {
        id: 570,
        value: 4,
        student_id: 24,
        task_id: 5,
      },
      {
        id: 571,
        value: 4,
        student_id: 24,
        task_id: 6,
      },
      {
        id: 572,
        value: 4,
        student_id: 24,
        task_id: 7,
      },
      {
        id: 573,
        value: 4,
        student_id: 24,
        task_id: 8,
      },
      {
        id: 574,
        value: 4,
        student_id: 24,
        task_id: 9,
      },
      {
        id: 575,
        value: 4,
        student_id: 24,
        task_id: 10,
      },
      {
        id: 576,
        value: 4,
        student_id: 24,
        task_id: 11,
      },
      {
        id: 577,
        value: 4,
        student_id: 24,
        task_id: 12,
      },
      {
        id: 578,
        value: 4,
        student_id: 24,
        task_id: 13,
      },
      {
        id: 579,
        value: 4,
        student_id: 24,
        task_id: 14,
      },
      {
        id: 580,
        value: 4,
        student_id: 24,
        task_id: 15,
      },
      {
        id: 581,
        value: 4,
        student_id: 24,
        task_id: 16,
      },
      {
        id: 582,
        value: 4,
        student_id: 24,
        task_id: 17,
      },
    ]);

    await queryInterface.sequelize.query(`SELECT setval('grades_id_seq', 582)`);

    return generatedReacords;
  },

  async down(queryInterface, Sequelize) {
    return await queryInterface.bulkDelete('grades', null, {});
  },
};
